baseURL      = 'https://arsho.dev/'
languageCode = 'en-us'
title        = 'Me'
theme        = 'introduction'

[params]
    themeStyle = 'dark'
    email      = 'mail@arsho.dev'

    [params.home]
        localTime  = true
        timeZone   = 'Asia/Tokyo'
        timeFormat = 'en-US'

    [[params.social]]
        url       = 'https://github.com/sho918'
        icon      = 'github'
        icon_pack = 'fab'
    [[params.social]]
        url       = 'mailto:mail@arsho.dev'
        icon      = 'envelope'
        icon_pack = 'fas'

[[menu.main]]
    name   = 'Home'
    url    = '#top'
    weight = 1
[[menu.main]]
    name   = 'Contact'
    url    = '#contact'
    weight = 0
